### ISSUE TITLE
مشکل در گذاشتن خط تیره

### ISSUE THREAD

**Issue by alifa13** [javadr/negar-gui#1]
سلام استاد علی فرشی زاده هستم یکی از دانشجویان شما در دانشگاه قم.
در نرم افزار شما که به خوبی ساخته شده و از شما ممنونم یک مشکل جزئی وجود دارد . هنگامی که خط تیره های پشت سرهم میگذاریم به خط تیره 4 میرسد به بقیه خط تیره ها نمی چسبد . همینطور به خط تیره 7ام و 10ام و 13ام و ... .
البته ممکن است از feature های برنامه باشد.
تاکید کنم که از ارزش کار شما کم نمی کند و برنامه خوبی نوشته شده است
نکته : این زمانی اتفاق می افتد که برای مثال خط تیره 4ام یا 10 را گذاشته باشید و بعد یک اسپیس قرار دهید و بقیه متنتان رو بنویسید .

**Comment by javadr** [comment]
ممنون از وقتی که گذاشتید. 

ببینید نکته اینجاست که هر سه خط تیره به یک خط کشیده یا همان Em-dash تبدیل می‌شود و دو خط تیره پشت سرم هم به En-dash. با توجه به این نکته رفتار برنامه درست است. پیشنهاد می‌کنم یک نگاهی هم به کد python-negar بیندازید تا بهتر دریابیدش.
