### ISSUE TITLE
Negar-gui crashes when 'QR code' is clicked

### ISSUE THREAD

**Issue by ALiwoto** [javadr/negar-gui#10]
# System Information
Windows11

# Negar-gui Information
Negar-gui-v7.0 [latest release build](https://github.com/javadr/negar-gui/releases/tag/0.7)

# Bug details
Clicking QR Code button will cause the whole application to crash (when there is something written in the text box).
![image](https://user-images.githubusercontent.com/70187458/230558784-2bb916bb-45e3-450c-82a4-45e9e241f8cf.png)

# Steps to reproduce
1. Download negar-gui's latest build from [release page](https://github.com/javadr/negar-gui/releases/tag/0.7).
2. Write something in the text box. (Yes, if you don't have anything written there, it won't crash).
3. Now click on QR Code button and witness the application crashing.

<hr />

# Expected behavior
Do not crash. Even if something is wrong, show a dialog box and tell the user what is actually being done wrong. 🤔

# Actual behavior
It crashes: 💥

**Comment by ALiwoto** [comment]
I tried to debug this with vscode (so I can get a traceback to attach to this issue), but then encountered #12. I think it's better first we fix that issue, then come back to this one.

**Comment by javadr** [comment]
I have no issue!
I've downloaded the file and run it with `wine`. It works like a charm. 
Could you check it via the other version of Windows?

**Comment by javadr** [comment]
Could you check that does it work via `pip` installation or not?
If it is ok, it means we have lost some of its dependencies in our workflow setup.

**Comment by ALiwoto** [comment]
Sure, I will try the pip version.

**Comment by ALiwoto** [comment]
@javadr btw, if you would like GitHub to close a certain issue automatically, you can use commit messages that contains these words in them:
  - `fixes #10`
  - `Resolves #10`

Or so (you used `fix issue #10`, so GitHub didn't detect it).

**Comment by javadr** [comment]
Thanks for your comment.

**Comment by ALiwoto** [comment]
@javadr can I find you in university today? At ~3:30PM.

**Comment by javadr** [comment]
No, you can't. 
We are able to have a meeting session at 17:30 or the next day.
