### ISSUE TITLE
Compiled version for Windows?

### ISSUE THREAD

**Issue by rayman3003** [javadr/negar-gui#2]
Can we have a compiled version of negar-gui in release section for Windows?

**Comment by javadr** [comment]
In which platform?

**Comment by rayman3003** [comment]
Windows

**Comment by javadr** [comment]
There are two points:
1- The standalone binary file would be around 80MB since it needs Qt GUI. 
2- I have no Windows! 

If you can handle the first issue, I'll manage the second one.:smile:

**Comment by rayman3003** [comment]
> If you can handle the first issue, I'll manage the second one.😄

Yeap that's OK.. Thank u. 👍😅

**Comment by ALiwoto** [comment]
But how much time would it need to compile the whole binary each time? (asking since you mentioned Qt GUI, because Telegram Desktop also uses Qt libraries and it takes around 2 hours to compile)

Perhaps we can setup a GitHub action (Continuous Integration) on the repository and it builds binaries and uploads Artifacts to repository's release page on each git push.

**Comment by javadr** [comment]
Making a binary on my Linux (with SSD) takes more than 20 mins, see below:
```
________________________________________________________
Executed in  591.59 secs    fish           external
usr time   40.94 mins    0.00 micros   40.94 mins
sys time    0.89 mins  483.00 micros    0.89 mins
```

I think because of this, I've ignored making a binary version.
BTW, your idea seems more feasible. 
Thanks

**Comment by rayman3003** [comment]
negar-gui is a good unique app; & I'm sure windows users will love it. Since a good-working right-to-left language supporting unicode text editor, is hard to find in windows platform.

**Comment by ALiwoto** [comment]
@javadr I can help on adding the GitHub action and release process; would you please tell me which commands did you use to build the binary?

**Comment by javadr** [comment]
@ALiwoto Thank you. I've tested two approaches: 1. `nuitka`, and 2. `pyinstaller`. 
I think it would be better to talk about that in person. See you next week.

**Comment by javadr** [comment]
@ALiwoto Is there any new update?
