### ISSUE TITLE
Disabling the Revision

### ISSUE THREAD

**Issue by rayman3003** [javadr/negar-gui#5]
Could u please add an option to disabling the Revision windows.

Bcuz for me, the Revision windows is not always necessary; But currently it occupies the half of the GUI.

So if there is an option to disable/enable the Revision window, I could have a fullscreen space for the Original section.

Thank u.

**Comment by javadr** [comment]
added. 
get ver 0.4.1, use `Ctrl+F` to toggle between full-screen/normal mode.
