### ISSUE TITLE
Bigger size of the Font

### ISSUE THREAD

**Issue by rayman3003** [javadr/negar-gui#6]
Currently, the negar app has some few sizes of fonts; & even the largest size of the font, is not big enough! Specially for high-resolution monitors.

So if it is possible to increase the size of the fonts even more, it could be awesome. For example something like 3 or 4 times larger than the current biggest size.

Thank u.

**Comment by javadr** [comment]
Although 40 point font size is good enough on my machine, I've changed the maximum size to 72 point. 
Could you test it (ver 0.4.2) and let me know your idea about that?

**Comment by rayman3003** [comment]
Thank u very much. 72 point is almost good enough for my 2K monitor. But I think if u just increase it a little bigger 🤌 to something like 100 points, it would be good enough for 4K monitors too! 😅

**Comment by javadr** [comment]
Updated to 84-point size by version 0.6.1

**Comment by rayman3003** [comment]
Thank u very much. 🙏
