### ISSUE TITLE
Black background

### ISSUE THREAD

**Issue by rayman3003** [javadr/negar-gui#7]
Currently the background is white & the font is black.

If u add an optional option that allows the user to make it negative, it could be more user-freindly for users that prefer black-themed styles. (Black theme is a very popular style in modern apps).

I mean an option to change to black background & white font.

**Comment by javadr** [comment]
Thanks for your suggestion. 
I will work on it in the near future.

**Comment by rayman3003** [comment]
Awesome & thank u very much.

**Comment by javadr** [comment]
done in ver 0.6
