### ISSUE TITLE
Ctrl + S = Save?

### ISSUE THREAD

**Issue by rayman3003** [javadr/negar-gui#8]
Currently the "Ctrl + S" hotkey is being used for another command. But in almost all other apps, it is used for saving.

Having "Ctrl + S" for saving, allows users to save the documents, periodically & without any hassle. 

So if it is possible, please add a saving option, with "Ctrl + S" hotkey for it.

**Comment by javadr** [comment]
As you know, we have `Ctrl+E` to export the processed text. 
Do you mean it should be changed to `Ctrl+S‍‍‍`?

**Comment by rayman3003** [comment]
> As you know, we have `Ctrl+E` to export the processed text. Do you mean it should be changed to `Ctrl+S‍‍‍`?

Two things:

1- Yeap, It's better to change to Ctrl+S. Bcuz it's a common thing in most apps.

2- We need two saving options:

A) Save (with Ctrl+S‍‍‍ hotkey): that save the current document to a new or the previously saved file.

B) Save As: That saves the document to a new file.

For a better explanation, I suggest to download & try this popular text editor:

https://www.emeditor.com/download/

& type something in it & then try to save it (with Ctrl+S‍‍‍). It asks for a filename to save it. After the first save, type more in the current document & then again hit the Ctrl+S‍‍‍. As u can see, it won't ask for a filename this time. It just saves to the previously saved file.

I'm looking for a saving option in Negar, just like the one in EmEditor.

**Comment by javadr** [comment]
Thanks for your description. 
Got what you meant. 

I'll work on it.

**Comment by javadr** [comment]
done.

**Comment by javadr** [comment]
@rayman3003 
I have made another update to save all configurations. 
Could you test it on Windows and let me know if it works without flaws?

**Comment by rayman3003** [comment]
> Could you test it on Windows and let me know if it works without flaws?

Yeap. It works without problem.

But it seems that extension is missing!

When I use "save as" option, it saves the document, without *.txt at the end. It saves it with just a name.

![2023-08-16 09_52_11-Window](https://github.com/javadr/negar-gui/assets/17022701/eca83e21-be73-41c4-b0d4-860953c3ae4a)

But I think it's better that it saves it as *.txt, automatically.

![2023-08-16 09_52_36-Window](https://github.com/javadr/negar-gui/assets/17022701/eb79a150-a3ec-4663-bb4d-edf0b542c8f6)

**Comment by javadr** [comment]
Thanks for your suggestion. 
Done. Get version 0.8.2.
