### ISSUE TITLE
Settings -> interactive keyboard has no icon set for it

### ISSUE THREAD

**Issue by ALiwoto** [javadr/negar-gui#9]
# System Information
Windows11

# Negar-gui Information
Negar-gui-v7.0 [latest release build](https://github.com/javadr/negar-gui/releases/tag/0.7)

# Bug details
As seen in the screenshot below
![image](https://user-images.githubusercontent.com/70187458/230556758-f1e25a50-792f-4d1e-a2e2-644c8489c8df.png)
there is no icon set for the button.

# Steps to reproduce
1. Download negar-gui's latest build from [release page](https://github.com/javadr/negar-gui/releases/tag/0.7).
2. open the application and click on `settings`.
3. You will notice that there is no icon set for `interactive keyboard` (also that button does nothing when it's clicked; is it expected?)

<hr />

# Expected behavior
Having an icon.

# Actual behavior
No icon found for it.

**Comment by javadr** [comment]
This is a checkbox. We have this pattern in other menus like `settings -> editing options`. 
There is no need for an icon!
